/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Toko;

import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eclips
 */
public class DataBarang extends javax.swing.JFrame {
  Koneksi Koneksi = new Koneksi();

  private DefaultTableModel model;

  private void autonumber() {
    try {
      Connection c = Koneksi.getKoneksi();
      Statement s = c.createStatement();
      String sql = "SELECT * FROM barang ORDER BY ID_Barang DESC";
      ResultSet r = s.executeQuery(sql);
      if (r.next()) {
        String NoFaktur = r.getString("ID_Barang").substring(2);
        String BR = "" + (Integer.parseInt(NoFaktur) + 1);
        String Nol = "";

        if (BR.length() == 1) {
          Nol = "00";
        } else if (BR.length() == 2) {
          Nol = "0";
        } else if (BR.length() == 3) {
          Nol = "";
        }
        txIDBarang.setText("BR" + Nol + BR);
      } else {
        txIDBarang.setText("BR001");
        r.close();
        s.close();
      }
    } catch (Exception e) {
      System.out.println("autonumber error");
    }
  }

  public void clear() {
    txNamaBarang.setText("");
    txHargaBeli.setText("");
    txHargaJual.setText("");
    txStok.setText("");
  }

  public void loadData() {
    model.getDataVector().removeAllElements();

    model.fireTableDataChanged();

    try {
      Connection c = Koneksi.getKoneksi();
      Statement s = c.createStatement();

      String sql = "SELECT * FROM barang";
      ResultSet r = s.executeQuery(sql);

      while (r.next()) {
        Object[] o = new Object[7];
        o[0] = r.getString("ID_Barang");
        o[1] = r.getString("Nama_Barang");
        o[2] = r.getString("Jenis");
        o[3] = r.getString("Ukuran");
        o[4] = r.getString("HargaBeli");
        o[5] = r.getString("HargaJual");
        o[6] = r.getString("Stok");

        model.addRow(o);
      }
      r.close();
      s.close();
    } catch (Exception e) {
      System.out.println("Error!. Terjadi Kesalahan");
    }
  }

  public void cariData() {
    DefaultTableModel tabel = new DefaultTableModel();

    tabel.addColumn("ID Barang");
    tabel.addColumn("Nama Barang");
    tabel.addColumn("Jenis");
    tabel.addColumn("Ukuran");
    tabel.addColumn("HargaBeli");
    tabel.addColumn("HargaJual");
    tabel.addColumn("Stok");

    try {
      Connection c = Koneksi.getKoneksi();
      String sql = "SELECT * FROM barang WHERE ID_Barang LIKE '%" + txCariData.getText() + "%' OR Nama_Barang LIKE '%" + txCariData.getText() + "%'";
      Statement stat = c.createStatement();
      ResultSet rs = stat.executeQuery(sql);
      while (rs.next()) {
        tabel.addRow(new Object[] {
            rs.getString(1),
            rs.getString(2),
            rs.getString(3),
            rs.getString(4),
            rs.getString(5),
            rs.getString(6),
            rs.getString(7),
        });
      }
      jTable1.setModel(tabel);
    } catch (Exception e) {
      System.out.println("Error. mencari data gagal");
    } finally {
    }
  }

  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataBarang.class.getName());

  /**
   * Creates new form DataBarang
   */
  public DataBarang() {
    initComponents();
    this.setLocationRelativeTo(null);

    model = new DefaultTableModel();

    jTable1.setModel(model);

    model.addColumn("ID_Barang");
    model.addColumn("Nama_Barang");
    model.addColumn("Jenis");
    model.addColumn("Ukuran");
    model.addColumn("HargaBeli");
    model.addColumn("HargaJual");
    model.addColumn("Stok");

    loadData();
    autonumber();
    btnEdit.setEnabled(false);
    btnBatal.setEnabled(false);
    btnHapus.setEnabled(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
  // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txIDBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNamaBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txHargaBeli = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txHargaJual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txStok = new javax.swing.JTextField();
        cbJenisBarang = new javax.swing.JComboBox<>();
        cbUkuran = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txCariData = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("DATA BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(263, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(262, 262, 262))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID Barang");

        txIDBarang.addActionListener(this::txIDBarangActionPerformed);

        jLabel3.setText("Nama Barang");

        jLabel4.setText("Jenis Barang");

        jLabel5.setText("Ukuran");

        jLabel7.setText("Harga Beli");

        jLabel8.setText("Harga Jual");

        txHargaJual.addActionListener(this::txHargaJualActionPerformed);

        jLabel9.setText("Stok");

        txStok.addActionListener(this::txStokActionPerformed);

        cbJenisBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baju", "Celana", "Jaket", "Kemeja" }));

        cbUkuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L", "XL", "XXL" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txIDBarang)
                    .addComponent(txNamaBarang)
                    .addComponent(cbJenisBarang, 0, 179, Short.MAX_VALUE)
                    .addComponent(cbUkuran, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txHargaBeli)
                    .addComponent(txHargaJual)
                    .addComponent(txStok, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txIDBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbUkuran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel6.setText("Cari Data");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(this::btnHapusActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txCariData, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txCariData, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

  private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEditActionPerformed
    int i = jTable1.getSelectedRow();
    if (i == -1) {
      return;
    }

    String id = (String) model.getValueAt(i, 0);
    String nama = txNamaBarang.getText();
    String jenis = (String) cbJenisBarang.getSelectedItem();
    String ukuran = (String) cbUkuran.getSelectedItem();
    String hargaBeli = txHargaBeli.getText();
    String hargaJual = txHargaJual.getText();
    String Stok = txStok.getText();

    try {
      Connection c = Koneksi.getKoneksi();
      String sql = "UPDATE barang SET Nama_Barang = ?, Jenis = ?, Ukuran = ?, HargaBeli = ?, HargaJual = ?, Stok = ? WHERE ID_Barang = ?";
      PreparedStatement p = c.prepareStatement(sql);
      p.setString(1, nama);
      p.setString(2, jenis);
      p.setString(3, ukuran);
      p.setString(4, hargaBeli);
      p.setString(5, hargaJual);
      p.setString(6, Stok);
      p.setString(7, id);
      
      p.executeUpdate();
      p.close();
      JOptionPane.showMessageDialog(null, "Data berhasil di Update");
      btnSimpan.setEnabled(true);
      btnEdit.setEnabled(false);
      btnBatal.setEnabled(false);
      btnHapus.setEnabled(false);
      clear();
    } catch (Exception e) {
      System.out.println("Error gagal update");
    } finally {
      loadData();
      autonumber();
    }
  }// GEN-LAST:event_btnEditActionPerformed
  
  private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHapusActionPerformed
    int i = jTable1.getSelectedRow();
    if (i == -1) {
      return;
    }
    
    String id = (String) model.getValueAt(i, 0);

    int pernyataan = JOptionPane.showConfirmDialog(null, "Apakah Yakin data akan dihapus", "Konfirmasi", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
    if (pernyataan == JOptionPane.OK_OPTION){ 
      try {
        Connection c = Koneksi.getKoneksi();
        String sql = "DELETE FROM barang WHERE ID_Barang = ?";
        PreparedStatement p = c.prepareStatement(sql);
        p.setString(1, id);
        p.executeUpdate();
        p.close();
        JOptionPane.showMessageDialog(null, "Data Terhapus");
      } catch (Exception e) {
        System.out.println("Terjadi Kesalahan");
      } finally {
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        loadData();
        autonumber();
        clear();
      }
    }
    if (pernyataan == JOptionPane.CANCEL_OPTION){

    }
  }// GEN-LAST:event_btnHapusActionPerformed
  
  private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSimpanActionPerformed
    String id = txIDBarang.getText();
    String nama = txNamaBarang.getText();
    String jenis = (String) cbJenisBarang.getSelectedItem();
    String ukuran = (String) cbUkuran.getSelectedItem();
    String hargaBeli = txHargaBeli.getText();
    String hargaJual = txHargaJual.getText();
    String stok = txStok.getText();

    if (nama.isEmpty() || hargaBeli.isEmpty() || hargaJual.isEmpty() || stok.isEmpty()) {
      JOptionPane.showMessageDialog(null, "Semua field harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
      return;
    }

    Connection c = Koneksi.getKoneksi();
    if (c == null) {
      JOptionPane.showMessageDialog(null, "Koneksi database gagal!", "Error", JOptionPane.ERROR_MESSAGE);
      return;
    }

    try {
      String sql = "INSERT INTO barang (ID_Barang, Nama_Barang, Jenis, Ukuran, HargaBeli, HargaJual, Stok) VALUES (?, ?, ?, ?, ?, ?, ?)";
      PreparedStatement p = c.prepareStatement(sql);
      p.setString(1, id);
      p.setString(2, nama);
      p.setString(3, jenis);
      p.setString(4, ukuran);
      p.setString(5, hargaBeli);
      p.setString(6, hargaJual);
      p.setString(7, stok);
      p.executeUpdate();
      p.close();
      JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
      loadData();
    } catch (Exception e) {
      e.printStackTrace();
      JOptionPane.showMessageDialog(null, "Gagal menyimpan data!\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
      autonumber();
      clear();
    }
  }// GEN-LAST:event_btnSimpanActionPerformed

  private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
    btnSimpan.setEnabled(false);
    btnEdit.setEnabled(true);
    btnHapus.setEnabled(true);
    btnBatal.setEnabled(true);

    int i = jTable1.getSelectedRow();
    if (i == -1) {
      return;
    }

    String id = (String) model.getValueAt(i, 0);
    String nama = (String) model.getValueAt(i, 1);
    String jenis = (String) model.getValueAt(i, 2);
    String ukuran = (String) model.getValueAt(i, 3);
    String hargaBeli = (String) model.getValueAt(i, 4);
    String hargaJual = (String) model.getValueAt(i, 5);
    String stok = (String) model.getValueAt(i, 6);

    txIDBarang.setText(id);
    txNamaBarang.setText(nama);
    cbJenisBarang.setSelectedItem(jenis);
    cbUkuran.setSelectedItem(ukuran);
    txHargaBeli.setText(hargaBeli);
    txHargaJual.setText(hargaJual);
    txStok.setText(stok);
  }// GEN-LAST:event_jTable1MouseClicked
  
  private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        clear();
        loadData();
        btnSimpan.setEnabled(true);
        btnEdit.setEnabled(false);
        btnHapus.setEnabled(false);
        btnBatal.setEnabled(false);
        autonumber();
    }//GEN-LAST:event_btnBatalActionPerformed

  private void txIDBarangActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txIDBarangActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txIDBarangActionPerformed

  private void txHargaJualActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txHargaJualActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txHargaJualActionPerformed

  private void txStokActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txStokActionPerformed
    // TODO add your handling code here:
  }// GEN-LAST:event_txStokActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the default
     * look and feel.
     * For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    // </editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new DataBarang().setVisible(true));
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbJenisBarang;
    private javax.swing.JComboBox<String> cbUkuran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txCariData;
    private javax.swing.JTextField txHargaBeli;
    private javax.swing.JTextField txHargaJual;
    private javax.swing.JTextField txIDBarang;
    private javax.swing.JTextField txNamaBarang;
    private javax.swing.JTextField txStok;
    // End of variables declaration//GEN-END:variables
}
